//
// gls_core.idl  glScript ActiveScript interfaces for core script objects.
// 
// This file is part of glScript project.
//
//   glScript is free software: you can redistribute it and/or modify
//   it under the terms of the GNU Lesser General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   glScript is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Lesser General Public License for more details.
//
//   You should have received a copy of the GNU Lesser General Public License
//   along with glScript. If not, see <http://www.gnu.org/licenses/>.
//
//   Copyright (c) 2012 Bal Bahadur Chettri
//
//   Author: Bal Bahadur Chettri (balu.chettri@gmail.com)
//
import "oaidl.idl";
import "ocidl.idl";

/* _GLScript_Array interface */
[object, uuid(99CD2524-E3A2-4fbc-993B-B7CD2F7F8CB7), dual, oleautomation, hidden, nonextensible]
interface _GLScript_Array : IDispatch {
    /* properties */

    /** Returns the internal type of array. */
    [propget] HRESULT type ([out,retval] int *pValue);

    /** Returns the length of array. */
    [propget] HRESULT length ([out,retval] int *pValue);

    /* methods */

    /** Returns an element at specified index. */
    HRESULT get ([in] int index, [out,retval] VARIANT *pValue);

    /** Sets an element at specified index. */
    HRESULT put ([in] int index, [in] VARIANT value);
}
