//
// gls_activescript_interfaces.idl  glscript ActiveScript interfaces for scripting model.
// 
// This file is part of glScript project.
//
//   glScript is free software: you can redistribute it and/or modify
//   it under the terms of the GNU Lesser General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   glScript is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Lesser General Public License for more details.
//
//   You should have received a copy of the GNU Lesser General Public License
//   along with glScript. If not, see <http://www.gnu.org/licenses/>.
//
//   Copyright (c) 2012 Bal Bahadur Chettri
//
//   Author: Bal Bahadur Chettri (balu.chettri@gmail.com)
//
import "oaidl.idl";
import "ocidl.idl";

import "..\..\include\glscript\activescript\gls_core.idl";

/* GLScript library */
[uuid(922C6F46-C588-47ea-99C1-4DDADA27FF9F), version(1.0), helpstring ("GLScript library")]
library LIBGLScript 
{
    importlib("stdole2.tlb");

    /* interfaces */

    /* _GLScript_Console interface */
    [object, uuid(DE2FED75-70CD-440d-9F20-ADF8AD48C5F4), dual, oleautomation, hidden, nonextensible]
    interface _GLScript_Console : IDispatch {
        /* methods */
        HRESULT log ([in] VARIANT msg);
        HRESULT warn ([in] VARIANT msg);
        HRESULT error ([in] VARIANT msg);
        HRESULT clear ();
    };

    /* _GLScript_Engine interface */
    [object, uuid(FA6780B7-0734-4907-A0AB-FFB88C3FCCA3), dual, oleautomation, hidden, nonextensible]
    interface _GLScript_Engine : IDispatch {
        /* properties */
        [propget] HRESULT version ([out, retval] short *pValue);
        [propget] HRESULT native ([out, retval] VARIANT_BOOL *pValue);
        [propput] HRESULT native ([in] VARIANT_BOOL value);
        [propget] HRESULT gles ([out, retval] VARIANT_BOOL *pValue);
        [propput] HRESULT gles ([in] VARIANT_BOOL value);
        [propget] HRESULT glver ([out, retval] VARIANT_BOOL *pValue);       
        [propget] HRESULT shader ([out, retval] BSTR *pValue);
        [propput] HRESULT shader ([in] BSTR value);
        [propget] HRESULT windowTitle ([out,retval] BSTR *pValue);
        [propput] HRESULT windowTitle ([in] BSTR value);
        [propget] HRESULT windowWidth ([out,retval] int *pValue);
        [propput] HRESULT windowWidth ([in] int value);
        [propget] HRESULT windowHeight ([out,retval] int *pValue);
        [propput] HRESULT windowHeight ([in] int value);
        [propget] HRESULT viewPortLeft ([out,retval] int *pValue);
        [propput] HRESULT viewPortLeft ([in] int value);
        [propget] HRESULT viewPortTop ([out,retval] int *pValue);
        [propput] HRESULT viewPortTop ([in] int value);
        [propget] HRESULT viewPortWidth ([out,retval] int *pValue);
        [propput] HRESULT viewPortWidth ([in] int value);
        [propget] HRESULT viewPortHeight ([out,retval] int *pValue);
        [propput] HRESULT viewPortHeight ([in] int value);
        [propget] HRESULT ortho ([out,retval] VARIANT_BOOL *pValue);
        [propput] HRESULT ortho ([in] VARIANT_BOOL value);
        [propget] HRESULT animation ([out,retval] VARIANT_BOOL *pValue);
        [propput] HRESULT animation ([in] VARIANT_BOOL value);
        [propget] HRESULT frameRate ([out,retval] short *pValue);
        [propput] HRESULT frameRate ([in] short value);
        [propget] HRESULT fps ([out, retval] short *pValue);        

        /* methods */
        HRESULT require ([in] BSTR path, [in, optional] VARIANT options, [out,retval] IDispatch **ppDispatch);
        
        HRESULT byteArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT ubyteArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT shortArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT ushortArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT intArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT uintArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT floatArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
        HRESULT doubleArray ([in] VARIANT varArrayConfig, [out,retval] _GLScript_Array **pOutArray);
    }

    /* _GLScript_Context interface */
    [object, uuid(83711F8E-7E57-4016-8474-BFCF376B0F46), dual, oleautomation, hidden, nonextensible]
    interface _GLScript_Context : IDispatch {
        HRESULT flush ();
        HRESULT glAccum ([in] unsigned int op, [in] float value);
        HRESULT glAlphaFunc ([in] unsigned int func, [in] float ref1);
        HRESULT glAreTexturesResident ([in] int n, [in] _GLScript_Array *textures, [in] _GLScript_Array *residences, [out,retval] unsigned char *pRet);
        HRESULT glArrayElement ([in] int i);
        HRESULT glBegin ([in] unsigned int mode);
        HRESULT glBindTexture ([in] unsigned int target, [in] unsigned int texture);
        HRESULT glBitmap ([in] int width, [in] int height, [in] float xorig, [in] float yorig, [in] float xmove, [in] float ymove, [in] _GLScript_Array *bitmap);
        HRESULT glBlendFunc ([in] unsigned int sfactor, [in] unsigned int dfactor);
        HRESULT glCallList ([in] unsigned int list);
        HRESULT glCallLists ([in] int n, [in] unsigned int type, [in] _GLScript_Array *lists);
        HRESULT glClear ([in] unsigned int mask);
        HRESULT glClearAccum ([in] float red, [in] float green, [in] float blue, [in] float alpha);
        HRESULT glClearColor ([in] float red, [in] float green, [in] float blue, [in] float alpha);
        HRESULT glClearDepth ([in] double depth);
        HRESULT glClearIndex ([in] float c);
        HRESULT glClearStencil ([in] int s);

        HRESULT glClipPlane ([in] unsigned int plane, [in] _GLScript_Array *equation);
        HRESULT glColor3b ([in] signed char red, [in] signed char green, [in] signed char blue);
        HRESULT glColor3bv ([in] _GLScript_Array *v);
        HRESULT glColor3d ([in] double red, [in] double green, [in] double blue);
        HRESULT glColor3dv ([in] _GLScript_Array *v);
        HRESULT glColor3f ([in] float red, [in] float green, [in] float blue);
        HRESULT glColor3fv ([in] _GLScript_Array *v);
        HRESULT glColor3i ([in] int red, [in] int green, [in] int blue);
        HRESULT glColor3iv ([in] _GLScript_Array *v);
        HRESULT glColor3s ([in] short red, [in] short green, [in] short blue);
        HRESULT glColor3sv ([in] _GLScript_Array *v);
        HRESULT glColor3ub ([in] unsigned char red, [in] unsigned char green, [in] unsigned char blue);
        HRESULT glColor3ubv ([in] _GLScript_Array *v);
        HRESULT glColor3ui ([in] unsigned int red, [in] unsigned int green, [in] unsigned int blue);
        HRESULT glColor3uiv ([in] _GLScript_Array *v);
        HRESULT glColor3us ([in] unsigned short red, [in] unsigned short green, [in] unsigned short blue);
        HRESULT glColor3usv ([in] _GLScript_Array *v);
        HRESULT glColor4b ([in] signed char red, [in] signed char green, [in] signed char blue, [in] signed char alpha);
        HRESULT glColor4bv ([in] _GLScript_Array *v);
        HRESULT glColor4d ([in] double red, [in] double green, [in] double blue, [in] double alpha);
        HRESULT glColor4dv ([in] _GLScript_Array *v);
        HRESULT glColor4f ([in] float red, [in] float green, [in] float blue, [in] float alpha);
        HRESULT glColor4fv ([in] _GLScript_Array *v);
        HRESULT glColor4i ([in] int red, [in] int green, [in] int blue, [in] int alpha);
        HRESULT glColor4iv ([in] _GLScript_Array *v);
        HRESULT glColor4s ([in] short red, [in] short green, [in] short blue, [in] short alpha);
        HRESULT glColor4sv ([in] _GLScript_Array *v);
        HRESULT glColor4ub ([in] unsigned char red, [in] unsigned char green, [in] unsigned char blue, [in] unsigned char alpha);

        HRESULT glColor4ubv ([in] _GLScript_Array *v);
        HRESULT glColor4ui ([in] unsigned int red, [in] unsigned int green, [in] unsigned int blue, [in] unsigned int alpha);
        HRESULT glColor4uiv ([in] _GLScript_Array *v);
        HRESULT glColor4us ([in] unsigned short red, [in] unsigned short green, [in] unsigned short blue, [in] unsigned short alpha);
        HRESULT glColor4usv ([in] _GLScript_Array *v);
        HRESULT glColorMask ([in] char red, [in] char green, [in] char blue, [in] char alpha);
        HRESULT glColorMaterial ([in] unsigned int face, [in] unsigned int mode);
        HRESULT glColorPointer ([in] int size, [in] unsigned int type, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glCopyPixels ([in] int x, [in] int y, [in] int width, [in] int height, [in] unsigned int type);
        HRESULT glCopyTexImage1D ([in] unsigned int target, [in] int level, [in] unsigned int internalFormat, [in] int x, [in] int y, [in] int width, [in] int border);
        HRESULT glCopyTexImage2D ([in] unsigned int target, [in] int level, [in] unsigned int internalFormat, [in] int x, [in] int y, [in] int width, [in] int height, [in] int border);
        HRESULT glCopyTexSubImage1D ([in] unsigned int target, [in] int level, [in] int xoffset, [in] int x, [in] int y, [in] int width);
        HRESULT glCopyTexSubImage2D ([in] unsigned int target, [in] int level, [in] int xoffset, [in] int yoffset, [in] int x, [in] int y, [in] int width, [in] int height);
        HRESULT glCullFace ([in] unsigned int mode);
        HRESULT glDeleteLists ([in] unsigned int list, [in] int range);
        HRESULT glDeleteTextures ([in] int n, [in] _GLScript_Array *textures);
        HRESULT glDepthFunc ([in] unsigned int func);
        HRESULT glDepthMask ([in] char flag);
        HRESULT glDepthRange ([in] double zNear, [in] double zFar);
        HRESULT glDisable ([in] unsigned int cap);
        HRESULT glDisableClientState ([in] unsigned int array);
        HRESULT glDrawArrays ([in] unsigned int mode, [in] int first, [in] int count);
        HRESULT glDrawBuffer ([in] unsigned int mode);
        HRESULT glDrawElements ([in] unsigned int mode, [in] int count, [in] unsigned int type, [in] _GLScript_Array *indices);
        HRESULT glDrawPixels ([in] int width, [in] int height, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);

        HRESULT glEdgeFlag ([in] char flag);
        HRESULT glEdgeFlagPointer ([in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glEdgeFlagv ([in] _GLScript_Array *flag);
        HRESULT glEnable ([in] unsigned int cap);
        HRESULT glEnableClientState ([in] unsigned int array);
        HRESULT glEnd ([in] void);
        HRESULT glEndList ([in] void);
        HRESULT glEvalCoord1d ([in] double u);
        HRESULT glEvalCoord1dv ([in] _GLScript_Array *u);
        HRESULT glEvalCoord1f ([in] float u);
        HRESULT glEvalCoord1fv ([in] _GLScript_Array *u);
        HRESULT glEvalCoord2d ([in] double u, [in] double v);
        HRESULT glEvalCoord2dv ([in] _GLScript_Array *u);
        HRESULT glEvalCoord2f ([in] float u, [in] float v);
        HRESULT glEvalCoord2fv ([in] _GLScript_Array *u);
        HRESULT glEvalMesh1 ([in] unsigned int mode, [in] int i1, [in] int i2);
        HRESULT glEvalMesh2 ([in] unsigned int mode, [in] int i1, [in] int i2, [in] int j1, [in] int j2);
        HRESULT glEvalPoint1 ([in] int i);      
        HRESULT glEvalPoint2 ([in] int i, [in] int j);
        HRESULT glFeedbackBuffer ([in] int size, [in] unsigned int type, [in] _GLScript_Array *buffer);
        HRESULT glFinish ([in] void);
        HRESULT glFlush ([in] void);
        HRESULT glFogf ([in] unsigned int pname, [in] float param);
        HRESULT glFogfv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glFogi ([in] unsigned int pname, [in] int param);
        HRESULT glFogiv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glFrontFace ([in] unsigned int mode);
        HRESULT glFrustum ([in] double left, [in] double right, [in] double bottom, [in] double top, [in] double zNear, [in] double zFar);
        HRESULT glGenLists ([in] int range, [out,retval] unsigned int *pRetVal);
        HRESULT glGenTextures ([in] int n, [in] _GLScript_Array *textures);
        HRESULT glGetBooleanv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetClipPlane ([in] unsigned int plane, [in] _GLScript_Array *equation);
        HRESULT glGetDoublev ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetError ([out,retval] unsigned int *pRetVal);
        HRESULT glGetFloatv ([in] unsigned int pname, [in] _GLScript_Array *params);

        HRESULT glGetIntegerv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetLightfv ([in] unsigned int light, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetLightiv ([in] unsigned int light, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetMapdv ([in] unsigned int target, [in] unsigned int query, [in] _GLScript_Array *v);
        HRESULT glGetMapfv ([in] unsigned int target, [in] unsigned int query, [in] _GLScript_Array *v);
        HRESULT glGetMapiv ([in] unsigned int target, [in] unsigned int query, [in] _GLScript_Array *v);
        HRESULT glGetMaterialfv ([in] unsigned int face, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetMaterialiv ([in] unsigned int face, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetPixelMapfv ([in] unsigned int map, [in] _GLScript_Array *values);
        HRESULT glGetPixelMapuiv ([in] unsigned int map, [in] _GLScript_Array *values);
        HRESULT glGetPixelMapusv ([in] unsigned int map, [in] _GLScript_Array *values);
        HRESULT glGetPointerv ([in] unsigned int pname, [in] void* *params);
        HRESULT glGetPolygonStipple ([in] _GLScript_Array *mask);
        HRESULT glGetString ([in] unsigned int name, [out,retval] BSTR *pRetVal);
        HRESULT glGetTexEnvfv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexEnviv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexGendv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexGenfv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexGeniv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexImage ([in] unsigned int target, [in] int level, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glGetTexLevelParameterfv ([in] unsigned int target, [in] int level, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexLevelParameteriv ([in] unsigned int target, [in] int level, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexParameterfv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glGetTexParameteriv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glHint ([in] unsigned int target, [in] unsigned int mode);
        HRESULT glIndexMask ([in] unsigned int mask);
        HRESULT glIndexPointer ([in] unsigned int type, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glIndexd ([in] double c);
        HRESULT glIndexdv ([in] _GLScript_Array *c);
        HRESULT glIndexf ([in] float c);
        HRESULT glIndexfv ([in] _GLScript_Array *c);
        HRESULT glIndexi ([in] int c);
        HRESULT glIndexiv ([in] _GLScript_Array *c);
        HRESULT glIndexs ([in] short c);
        HRESULT glIndexsv ([in] _GLScript_Array *c);

        HRESULT glIndexub ([in] unsigned char c);
        HRESULT glIndexubv ([in] _GLScript_Array *c);
        HRESULT glInitNames ([in] void);
        HRESULT glInterleavedArrays ([in] unsigned int format, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glIsEnabled ([in] unsigned int cap, [out,retval] char *pRetVal);
        HRESULT glIsList ([in] unsigned int list, [out,retval] char *pRetVal);
        HRESULT glIsTexture ([in] unsigned int texture, [out,retval] char *pRetVal);
        HRESULT glLightModelf ([in] unsigned int pname, [in] float param);
        HRESULT glLightModelfv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glLightModeli ([in] unsigned int pname, [in] int param);
        HRESULT glLightModeliv ([in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glLightf ([in] unsigned int light, [in] unsigned int pname, [in] float param);
        HRESULT glLightfv ([in] unsigned int light, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glLighti ([in] unsigned int light, [in] unsigned int pname, [in] int param);
        HRESULT glLightiv ([in] unsigned int light, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glLineStipple ([in] int factor, [in] unsigned short pattern);
        HRESULT glLineWidth ([in] float width);
        HRESULT glListBase ([in] unsigned int base);
        HRESULT glLoadIdentity ([in] void);
        HRESULT glLoadMatrixd ([in] _GLScript_Array *m);
        HRESULT glLoadMatrixf ([in] _GLScript_Array *m);
        HRESULT glLoadName ([in] unsigned int name);
        HRESULT glLogicOp ([in] unsigned int opcode);
        HRESULT glMap1d ([in] unsigned int target, [in] double u1, [in] double u2, [in] int stride, [in] int order, [in] _GLScript_Array *points);
        HRESULT glMap1f ([in] unsigned int target, [in] float u1, [in] float u2, [in] int stride, [in] int order, [in] _GLScript_Array *points);
        HRESULT glMap2d ([in] unsigned int target, [in] double u1, [in] double u2, [in] int ustride, [in] int uorder, [in] double v1, [in] double v2, [in] int vstride, [in] int vorder, [in] _GLScript_Array *points);
        HRESULT glMap2f ([in] unsigned int target, [in] float u1, [in] float u2, [in] int ustride, [in] int uorder, [in] float v1, [in] float v2, [in] int vstride, [in] int vorder, [in] _GLScript_Array *points);
        HRESULT glMapGrid1d ([in] int un, [in] double u1, [in] double u2);
        HRESULT glMapGrid1f ([in] int un, [in] float u1, [in] float u2);
        HRESULT glMapGrid2d ([in] int un, [in] double u1, [in] double u2, [in] int vn, [in] double v1, [in] double v2);
        HRESULT glMapGrid2f ([in] int un, [in] float u1, [in] float u2, [in] int vn, [in] float v1, [in] float v2);
        HRESULT glMaterialf ([in] unsigned int face, [in] unsigned int pname, [in] float param);
        HRESULT glMaterialfv ([in] unsigned int face, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glMateriali ([in] unsigned int face, [in] unsigned int pname, [in] int param);

        HRESULT glMaterialiv ([in] unsigned int face, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glMatrixMode ([in] unsigned int mode);
        HRESULT glMultMatrixd ([in] _GLScript_Array *m);
        HRESULT glMultMatrixf ([in] _GLScript_Array *m);
        HRESULT glNewList ([in] unsigned int list, [in] unsigned int mode);
        HRESULT glNormal3b ([in] signed char nx, [in] signed char ny, [in] signed char nz);
        HRESULT glNormal3bv ([in] _GLScript_Array *v);
        HRESULT glNormal3d ([in] double nx, [in] double ny, [in] double nz);
        HRESULT glNormal3dv ([in] _GLScript_Array *v);
        HRESULT glNormal3f ([in] float nx, [in] float ny, [in] float nz);
        HRESULT glNormal3fv ([in] _GLScript_Array *v);
        HRESULT glNormal3i ([in] int nx, [in] int ny, [in] int nz);
        HRESULT glNormal3iv ([in] _GLScript_Array *v);
        HRESULT glNormal3s ([in] short nx, [in] short ny, [in] short nz);
        HRESULT glNormal3sv ([in] _GLScript_Array *v);
        HRESULT glNormalPointer ([in] unsigned int type, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glOrtho ([in] double left, [in] double right, [in] double bottom, [in] double top, [in] double zNear, [in] double zFar);
        HRESULT glPassThrough ([in] float token);
        HRESULT glPixelMapfv ([in] unsigned int map, [in] int mapsize, [in] _GLScript_Array *values);
        HRESULT glPixelMapuiv ([in] unsigned int map, [in] int mapsize, [in] _GLScript_Array *values);
        HRESULT glPixelMapusv ([in] unsigned int map, [in] int mapsize, [in] _GLScript_Array *values);
        HRESULT glPixelStoref ([in] unsigned int pname, [in] float param);
        HRESULT glPixelStorei ([in] unsigned int pname, [in] int param);
        HRESULT glPixelTransferf ([in] unsigned int pname, [in] float param);
        HRESULT glPixelTransferi ([in] unsigned int pname, [in] int param);
        HRESULT glPixelZoom ([in] float xfactor, [in] float yfactor);
        HRESULT glPointSize ([in] float size);
        HRESULT glPolygonMode ([in] unsigned int face, [in] unsigned int mode);
        HRESULT glPolygonOffset ([in] float factor, [in] float units);
        HRESULT glPolygonStipple ([in] _GLScript_Array *mask);
        HRESULT glPopAttrib ([in] void);
        HRESULT glPopClientAttrib ([in] void);
        HRESULT glPopMatrix ([in] void);
        HRESULT glPopName ([in] void);

        ////

        HRESULT glPrioritizeTextures ([in] int n, [in] _GLScript_Array *textures, [in] _GLScript_Array *priorities);
        HRESULT glPushAttrib ([in] unsigned int mask);
        HRESULT glPushClientAttrib ([in] unsigned int mask);
        HRESULT glPushMatrix ([in] void);
        HRESULT glPushName ([in] unsigned int name);
        HRESULT glRasterPos2d ([in] double x, [in] double y);
        HRESULT glRasterPos2dv ([in] _GLScript_Array *v);
        HRESULT glRasterPos2f ([in] float x, [in] float y);
        HRESULT glRasterPos2fv ([in] _GLScript_Array *v);
        HRESULT glRasterPos2i ([in] int x, [in] int y);
        HRESULT glRasterPos2iv ([in] _GLScript_Array *v);
        HRESULT glRasterPos2s ([in] short x, [in] short y);
        HRESULT glRasterPos2sv ([in] _GLScript_Array *v);
        HRESULT glRasterPos3d ([in] double x, [in] double y, [in] double z);
        HRESULT glRasterPos3dv ([in] _GLScript_Array *v);
        HRESULT glRasterPos3f ([in] float x, [in] float y, [in] float z);
        HRESULT glRasterPos3fv ([in] _GLScript_Array *v);
        HRESULT glRasterPos3i ([in] int x, [in] int y, [in] int z);
        HRESULT glRasterPos3iv ([in] _GLScript_Array *v);
        HRESULT glRasterPos3s ([in] short x, [in] short y, [in] short z);
        HRESULT glRasterPos3sv ([in] _GLScript_Array *v);
        HRESULT glRasterPos4d ([in] double x, [in] double y, [in] double z, [in] double w);
        HRESULT glRasterPos4dv ([in] _GLScript_Array *v);
        HRESULT glRasterPos4f ([in] float x, [in] float y, [in] float z, [in] float w);
        HRESULT glRasterPos4fv ([in] _GLScript_Array *v);
        HRESULT glRasterPos4i ([in] int x, [in] int y, [in] int z, [in] int w);
        HRESULT glRasterPos4iv ([in] _GLScript_Array *v);
        HRESULT glRasterPos4s ([in] short x, [in] short y, [in] short z, [in] short w);
        HRESULT glRasterPos4sv ([in] _GLScript_Array *v);
        HRESULT glReadBuffer ([in] unsigned int mode);
        HRESULT glReadPixels ([in] int x, [in] int y, [in] int width, [in] int height, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glRectd ([in] double x1, [in] double y1, [in] double x2, [in] double y2);
        HRESULT glRectdv ([in] _GLScript_Array *v1, [in] _GLScript_Array *v2);
        HRESULT glRectf ([in] float x1, [in] float y1, [in] float x2, [in] float y2);

        ////////////////////////////////////////////////////////////////////////////////////////////////

        HRESULT glRectfv ([in] _GLScript_Array *v1, [in] _GLScript_Array *v2);
        HRESULT glRecti ([in] int x1, [in] int y1, [in] int x2, [in] int y2);
        HRESULT glRectiv ([in] _GLScript_Array *v1, [in] _GLScript_Array *v2);
        HRESULT glRects ([in] short x1, [in] short y1, [in] short x2, [in] short y2);
        HRESULT glRectsv ([in] _GLScript_Array *v1, [in] _GLScript_Array *v2);
        HRESULT glRenderMode ([in] unsigned int mode, [out,retval] int *pRetVal);
        HRESULT glRotated ([in] double angle, [in] double x, [in] double y, [in] double z);
        HRESULT glRotatef ([in] float angle, [in] float x, [in] float y, [in] float z);
        HRESULT glScaled ([in] double x, [in] double y, [in] double z);
        HRESULT glScalef ([in] float x, [in] float y, [in] float z);
        HRESULT glScissor ([in] int x, [in] int y, [in] int width, [in] int height);
        HRESULT glSelectBuffer ([in] int size, [in] _GLScript_Array *buffer);
        HRESULT glShadeModel ([in] unsigned int mode);
        HRESULT glStencilFunc ([in] unsigned int func, [in] int ref, [in] unsigned int mask);
        HRESULT glStencilMask ([in] unsigned int mask);
        HRESULT glStencilOp ([in] unsigned int fail, [in] unsigned int zfail, [in] unsigned int zpass);
        HRESULT glTexCoord1d ([in] double s);
        HRESULT glTexCoord1dv ([in] _GLScript_Array *v);
        HRESULT glTexCoord1f ([in] float s);
        HRESULT glTexCoord1fv ([in] _GLScript_Array *v);
        HRESULT glTexCoord1i ([in] int s);
        HRESULT glTexCoord1iv ([in] _GLScript_Array *v);
        HRESULT glTexCoord1s ([in] short s);
        HRESULT glTexCoord1sv ([in] _GLScript_Array *v);
        HRESULT glTexCoord2d ([in] double s, [in] double t);
        HRESULT glTexCoord2dv ([in] _GLScript_Array *v);
        HRESULT glTexCoord2f ([in] float s, [in] float t);
        HRESULT glTexCoord2fv ([in] _GLScript_Array *v);
        HRESULT glTexCoord2i ([in] int s, [in] int t);
        HRESULT glTexCoord2iv ([in] _GLScript_Array *v);
        HRESULT glTexCoord2s ([in] short s, [in] short t);
        HRESULT glTexCoord2sv ([in] _GLScript_Array *v);
        HRESULT glTexCoord3d ([in] double s, [in] double t, [in] double r);
        HRESULT glTexCoord3dv ([in] _GLScript_Array *v);
        HRESULT glTexCoord3f ([in] float s, [in] float t, [in] float r);

        //////////////////////////

        HRESULT glTexCoord3fv ([in] _GLScript_Array *v);
        HRESULT glTexCoord3i ([in] int s, [in] int t, [in] int r);
        HRESULT glTexCoord3iv ([in] _GLScript_Array *v);
        HRESULT glTexCoord3s ([in] short s, [in] short t, [in] short r);
        HRESULT glTexCoord3sv ([in] _GLScript_Array *v);
        HRESULT glTexCoord4d ([in] double s, [in] double t, [in] double r, [in] double q);
        HRESULT glTexCoord4dv ([in] _GLScript_Array *v);
        HRESULT glTexCoord4f ([in] float s, [in] float t, [in] float r, [in] float q);
        HRESULT glTexCoord4fv ([in] _GLScript_Array *v);
        HRESULT glTexCoord4i ([in] int s, [in] int t, [in] int r, [in] int q);
        HRESULT glTexCoord4iv ([in] _GLScript_Array *v);
        HRESULT glTexCoord4s ([in] short s, [in] short t, [in] short r, [in] short q);
        HRESULT glTexCoord4sv ([in] _GLScript_Array *v);
        HRESULT glTexCoordPointer ([in] int size, [in] unsigned int type, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glTexEnvf ([in] unsigned int target, [in] unsigned int pname, [in] float param);
        HRESULT glTexEnvfv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexEnvi ([in] unsigned int target, [in] unsigned int pname, [in] int param);
        HRESULT glTexEnviv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexGend ([in] unsigned int coord, [in] unsigned int pname, [in] double param);
        HRESULT glTexGendv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexGenf ([in] unsigned int coord, [in] unsigned int pname, [in] float param);
        HRESULT glTexGenfv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexGeni ([in] unsigned int coord, [in] unsigned int pname, [in] int param);
        HRESULT glTexGeniv ([in] unsigned int coord, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexImage1D ([in] unsigned int target, [in] int level, [in] int internalformat, [in] int width, [in] int border, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glTexImage2D ([in] unsigned int target, [in] int level, [in] int internalformat, [in] int width, [in] int height, [in] int border, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glTexParameterf ([in] unsigned int target, [in] unsigned int pname, [in] float param);
        HRESULT glTexParameterfv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexParameteri ([in] unsigned int target, [in] unsigned int pname, [in] int param);
        HRESULT glTexParameteriv ([in] unsigned int target, [in] unsigned int pname, [in] _GLScript_Array *params);
        HRESULT glTexSubImage1D ([in] unsigned int target, [in] int level, [in] int xoffset, [in] int width, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glTexSubImage2D ([in] unsigned int target, [in] int level, [in] int xoffset, [in] int yoffset, [in] int width, [in] int height, [in] unsigned int format, [in] unsigned int type, [in] _GLScript_Array *pixels);
        HRESULT glTranslated ([in] double x, [in] double y, [in] double z);
        HRESULT glTranslatef ([in] float x, [in] float y, [in] float z);
        HRESULT glVertex2d ([in] double x, [in] double y);
        HRESULT glVertex2dv ([in] _GLScript_Array *v);
        HRESULT glVertex2f ([in] float x, [in] float y);
        HRESULT glVertex2fv ([in] _GLScript_Array *v);
        HRESULT glVertex2i ([in] int x, [in] int y);
        HRESULT glVertex2iv ([in] _GLScript_Array *v);
        HRESULT glVertex2s ([in] short x, [in] short y);
        HRESULT glVertex2sv ([in] _GLScript_Array *v);
        HRESULT glVertex3d ([in] double x, [in] double y, [in] double z);
        HRESULT glVertex3dv ([in] _GLScript_Array *v);
        HRESULT glVertex3f ([in] float x, [in] float y, [in] float z);
        HRESULT glVertex3fv ([in] _GLScript_Array *v);
        HRESULT glVertex3i ([in] int x, [in] int y, [in] int z);
        HRESULT glVertex3iv ([in] _GLScript_Array *v);
        HRESULT glVertex3s ([in] short x, [in] short y, [in] short z);
        HRESULT glVertex3sv ([in] _GLScript_Array *v);
        HRESULT glVertex4d ([in] double x, [in] double y, [in] double z, [in] double w);
        HRESULT glVertex4dv ([in] _GLScript_Array *v);
        HRESULT glVertex4f ([in] float x, [in] float y, [in] float z, [in] float w);
        HRESULT glVertex4fv ([in] _GLScript_Array *v);
        HRESULT glVertex4i ([in] int x, [in] int y, [in] int z, [in] int w);
        HRESULT glVertex4iv ([in] _GLScript_Array *v);
        HRESULT glVertex4s ([in] short x, [in] short y, [in] short z, [in] short w);
        HRESULT glVertex4sv ([in] _GLScript_Array *v);
        HRESULT glVertexPointer ([in] int size, [in] unsigned int type, [in] int stride, [in] _GLScript_Array *pointer);
        HRESULT glViewport ([in] int x, [in] int y, [in] int width, [in] int height);
    }

}/* GLScript library */
